{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Sample Jokes API",
    "description" : "This is the example Swagger specfiication for the https://official-joke-api.appspot.com/random_joke",
    "version" : "0.1.9"
  },
  "servers" : [ {
    "url" : "https://official-joke-api.appspot.com/",
    "description" : "This is a fee app available"
  } ],
  "paths" : {
    "/random_joke" : {
      "get" : {
        "summary" : "Returns a joke",
        "description" : "This end poin returns an random joke out of a list of jokes.",
        "responses" : {
          "200" : {
            "description" : "A Joke Object",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "inline_response_200" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1
          },
          "type" : {
            "type" : "string",
            "example" : "general"
          },
          "setup" : {
            "type" : "string",
            "example" : "What do you call a boomerang that won't come back?"
          },
          "punchline" : {
            "type" : "string",
            "example" : "A Stick."
          }
        }
      }
    }
  }
}